POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/json

{
    "email": "clark@test.com", 
    "password": "passclark", 
    "fullname":"Clark Kent"
}

###

POST http://localhost:3000/signin HTTP/1.1
Content-Type: application/json

{
    "email": "clark@test.com", 
    "password": "passclark"
}
###

POST http://5b48-2400-adc1-128-6300-9c68-6ca7-6193-96af.ngrok.io/signin
Content-Type: application/json

{
    "email": "clark@test.com", 
    "password": "passclark"
}

###
GET http://localhost:3000/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiI2MzRmN2Q4Yzk2YzhmYmU1MzE4OTRiMjEiLCJpYXQiOjE2NjYxNTM4Njh9.xz6VVe4fPrCK_GCAVAg3r_n0uW82zx2vhdphZwpFKSc

